// Code generated by goctl. DO NOT EDIT.
package types

type SendRequest struct {
	Code              string       `json:"code"`
	MessageTemplateId int64        `json:"messageTemplateId"`
	MessageParam      MessageParam `json:"messageParam"`
}

type MessageParam struct {
	Receiver  string                 `json:"receiver"`
	Variables map[string]interface{} `json:"variables,optional"`
	Extra     map[string]interface{} `json:"extra,optional"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
