// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"msg/app/msg-web/msg_api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/send",
				Handler: SendHandler(serverCtx),
			},
		},
	)
}
